---
# tasks file for vcd_vapp_vm_nic

- name: add vm nic
  vcd_vapp_vm_nic:
    user: acmeadmin
    password: VMware1!
    org: Acme
    vapp: vApp_system_2
    vm_name: "Tiny Linux template"
    vdc: ACME_PAYG
    network: External-VM-Network
    ip_allocation_mode: DHCP
    state: present
  register: output


- name: add vm nic output
  debug:
    msg: '{{ output }}'